# Generated by Django 2.2.11 on 2020-04-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=250)),
                ('animal_type', models.CharField(max_length=250)),
                ('custom_fields', models.TextField(blank=True)),
                ('mother_title', models.CharField(default='Mother', max_length=250)),
                ('father_title', models.CharField(default='Father', max_length=250)),
                ('coi_timeout', models.IntegerField(default=60)),
                ('mean_kinship_timeout', models.IntegerField(default=60)),
                ('metrics', models.BooleanField(default=False)),
                ('site_mode', models.CharField(blank=True, choices=[('mammal', 'Mammal'), ('poultry', 'Poultry')], default='mammal', max_length=13, null=True)),
                ('increment', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default=None, max_length=10, null=True)),
                ('active', models.BooleanField(default=False)),
                ('subscription_id', models.CharField(blank=True, max_length=250)),
                ('install_available', models.BooleanField(default=False)),
                ('admin_users', models.ManyToManyField(blank=True, related_name='admin_users', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributors', to=settings.AUTH_USER_MODEL)),
                ('read_only_users', models.ManyToManyField(blank=True, related_name='read_only_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('stripe_id', models.CharField(blank=True, max_length=50)),
                ('current_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
