# Generated by Django 2.1.7 on 2019-03-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedetail',
            old_name='animal',
            new_name='animal_type',
        ),
    ]
