# Generated by Django 2.1.9 on 2019-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdetail_current_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='subscription_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
