# Generated by Django 2.2.11 on 2020-06-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200416_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='pedigree_columns',
            field=models.CharField(default='reg_no,mean_kinship,name,dob,status,breed,sex', max_length=500),
        ),
    ]
