# Generated by Django 2.1.7 on 2019-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190303_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='site_mode',
            field=models.CharField(choices=[('mammal', 'Mammal'), ('poultry', 'Poultry')], default=None, max_length=13),
        ),
    ]
