# Generated by Django 2.2.9 on 2020-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200413_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='metrics',
            field=models.BooleanField(default=False),
        ),
    ]
