# Generated by Django 2.2.11 on 2020-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_attachedservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='organisation_or_society_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
