# Generated by Django 2.1.10 on 2019-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_attachedservice_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='father_title',
            field=models.CharField(default='Father', max_length=250),
        ),
        migrations.AddField(
            model_name='attachedservice',
            name='mother_title',
            field=models.CharField(default='Mother', max_length=250),
        ),
    ]
