# Generated by Django 2.2.24 on 2021-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_attachedservice_boltons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedservice',
            name='site_mode',
            field=models.CharField(blank=True, choices=[('mammal', 'Mammal'), ('poultry', 'Poultry')], default='poultry', max_length=13, null=True),
        ),
    ]
