# Generated by Django 2.2.24 on 2021-10-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0007_bolton_visible_to_public'),
        ('account', '0007_auto_20210718_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedservice',
            name='boltons',
        ),
        migrations.CreateModel(
            name='AttachedBolton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sub_id', models.CharField(blank=True, max_length=255)),
                ('increment', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default=None, max_length=10, null=True)),
                ('active', models.BooleanField(default=False)),
                ('bolton', models.ManyToManyField(blank=True, related_name='boltons', to='cloud_lines.Bolton')),
            ],
        ),
    ]
