# Generated by Django 2.2.5 on 2019-10-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_attachedservice_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedservice',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
