# Generated by Django 2.2.24 on 2021-10-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211012_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='boltons',
            field=models.ManyToManyField(blank=True, related_name='boltons', to='account.AttachedBolton'),
        ),
    ]
