# Generated by Django 2.2.4 on 2019-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191022_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='coi_timeout',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='attachedservice',
            name='mean_kinship_timeout',
            field=models.IntegerField(default=60),
        ),
    ]
