# Generated by Django 2.2.24 on 2021-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_attachedservice_boltons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='graphs',
            field=models.TextField(default='{"selected": [], "max_reached": false}', verbose_name='Dashboard Graphs'),
        ),
    ]
