# Generated by Django 2.2.24 on 2021-10-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0007_bolton_visible_to_public'),
        ('account', '0010_userdetail_graphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedbolton',
            name='bolton',
        ),
        migrations.AddField(
            model_name='attachedbolton',
            name='bolton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolton_service', to='cloud_lines.Bolton'),
        ),
    ]
