# Generated by Django 2.2.9 on 2020-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191209_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedservice',
            name='site_mode',
            field=models.CharField(blank=True, choices=[('mammal', 'Mammal'), ('poultry', 'Poultry')], default='mammal', max_length=13, null=True),
        ),
    ]
