# Generated by Django 2.2.24 on 2021-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20211019_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedbolton',
            name='bolton',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
