# Generated by Django 2.2.24 on 2021-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211026_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='data_protection_agreed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='data_protection_version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='privacy_agreed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='privacy_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
