# Generated by Django 2.2.27 on 2022-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211210_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedbolton',
            name='stripe_acct_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
