# Generated by Django 2.2.27 on 2022-08-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_attachedbolton_stripe_acct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='bn_stripe_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
