# Generated by Django 2.2.27 on 2022-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userdetail_bn_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='bn_stripe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
