# Generated by Django 2.2.27 on 2022-10-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_stripeaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnStripe',
            fields=[
                ('stripeaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.StripeAccount')),
                ('bn_cost_id', models.IntegerField(blank=True, default=0)),
                ('bn_child_cost_id', models.IntegerField(blank=True, default=0)),
            ],
            bases=('account.stripeaccount',),
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='bn_child_cost',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='bn_cost',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='ped_cost',
        ),
    ]
