# Generated by Django 2.2.27 on 2022-10-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20221012_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='bnstripe',
            name='bn_stripe_product_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
