# Generated by Django 2.2.27 on 2022-10-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20221012_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedbolton',
            name='increment',
        ),
        migrations.AddField(
            model_name='attachedbolton',
            name='stripe_payment_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
