# Generated by Django 2.2.27 on 2022-10-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20221018_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BnStripe',
        ),
    ]
