# Generated by Django 2.2.27 on 2022-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_delete_bnstripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='bn_child_cost_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='bn_cost_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='bn_stripe_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
