# Generated by Django 2.2.27 on 2022-11-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20221025_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='pedigree_charging',
            field=models.BooleanField(default=False),
        ),
    ]
