# Generated by Django 2.2.27 on 2023-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_stripeaccount_bn_charging'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='currency',
            field=models.CharField(blank=True, default='GBP', max_length=255),
        ),
    ]
