# Generated by Django 4.2.2 on 2023-10-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20230622_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='stripe_payment_token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
