# Generated by Django 4.2.2 on 2024-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_attachedservice_stripe_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedservice',
            name='pedigrees_visible',
            field=models.BooleanField(default=False),
        ),
    ]
