# Generated by Django 2.2.9 on 2020-04-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_prefix', models.CharField(help_text='Must be unique', max_length=100)),
                ('contact_name', models.CharField(blank=True, help_text='The primary contact for the breeder/owner', max_length=100)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone_number1', models.CharField(blank=True, max_length=100)),
                ('phone_number2', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('custom_fields', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False, help_text='Is the breeder currently active?')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
            ],
        ),
    ]
