# Generated by Django 2.1.9 on 2019-06-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone_number1', models.CharField(blank=True, max_length=100)),
                ('phone_number2', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
            ],
        ),
    ]
