# Generated by Django 2.2.11 on 2020-06-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breeder',
            options={'ordering': ['active']},
        ),
    ]
