# Generated by Django 2.1.2 on 2019-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='prefix',
            field=models.CharField(max_length=100),
        ),
    ]
