# Generated by Django 2.1.10 on 2019-07-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0002_breeder_custom_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeder',
            old_name='prefix',
            new_name='breeding_prefix',
        ),
    ]
