# Generated by Django 2.2.11 on 2020-06-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0002_auto_20200629_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breeder',
            options={},
        ),
    ]
