# Generated by Django 2.1.10 on 2019-07-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0003_auto_20190721_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='active',
            field=models.BooleanField(default=False, help_text='Is the breeder currently active?'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='breeding_prefix',
            field=models.CharField(help_text='Must be unique', max_length=100),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='contact_name',
            field=models.CharField(blank=True, help_text='The primary contact for the breeder/owner', max_length=100),
        ),
    ]
