# Generated by Django 2.2.11 on 2021-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0004_auto_20200723_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='active',
            field=models.BooleanField(default=False, help_text='Is the breeder currently active?', verbose_name='Status'),
        ),
    ]
