# Generated by Django 2.2.24 on 2021-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0006_auto_20210716_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeder',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='breeder',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='breeder',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='breeder',
            name='postcode',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='breeder',
            name='town',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
