# Generated by Django 2.2.24 on 2021-09-09 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breeder', '0007_auto_20210724_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeder', to=settings.AUTH_USER_MODEL),
        ),
    ]
