# Generated by Django 4.2.2 on 2024-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0009_alter_breeder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeder',
            name='data_visible',
            field=models.BooleanField(default=False, help_text='Is the breeder data visible to others?', verbose_name='Data Visible'),
        ),
    ]
