# Generated by Django 2.1.9 on 2019-06-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breed', '0001_initial'),
        ('pedigree', '0001_initial'),
        ('account', '0001_initial'),
        ('breeder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breed.Breed')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breeder.Breeder')),
                ('group_members', models.ManyToManyField(to='pedigree.Pedigree')),
            ],
        ),
    ]
