# Generated by Django 2.2.11 on 2020-04-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedigree', '0001_initial'),
        ('breed', '0001_initial'),
        ('account', '0002_auto_20200416_1409'),
        ('breeder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('edited', 'Edited'), ('unapproved', 'Unapproved'), ('approved', 'Approved')], default='approved', max_length=10, null=True)),
                ('group_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breed.Breed')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breeder.Breeder')),
                ('group_members', models.ManyToManyField(to='pedigree.Pedigree')),
            ],
            options={
                'get_latest_by': 'state',
            },
        ),
    ]
