# Generated by Django 2.1.5 on 2019-02-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedigree', '0002_pedigreesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_members', models.ManyToManyField(to='pedigree.Pedigree')),
            ],
        ),
    ]
