# Generated by Django 2.2.24 on 2021-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedgroup',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
