# Generated by Django 2.2.5 on 2019-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedgroup',
            name='state',
            field=models.CharField(choices=[('edited', 'Edited'), ('unapproved', 'Unapproved'), ('approved', 'Approved')], default='approved', max_length=10, null=True),
        ),
    ]
