# Generated by Django 2.1.5 on 2019-02-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedgroup',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2019-01-01 01:01'),
            preserve_default=False,
        ),
    ]
