# Generated by Django 2.1.7 on 2019-02-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0002_auto_20190130_1508'),
        ('breed_group', '0002_breedgroup_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedgroup',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breeder.Breeder'),
        ),
    ]
