# Generated by Django 2.2.5 on 2019-10-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breed_group', '0002_breedgroup_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedgroup',
            options={'get_latest_by': 'state'},
        ),
    ]
