# Generated by Django 2.2.24 on 2021-10-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_group', '0002_auto_20211026_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedgroup',
            name='group_name',
            field=models.CharField(blank=True, help_text='Must be unique', max_length=100, unique=True, verbose_name='Group ID'),
        ),
    ]
