# Generated by Django 2.1.7 on 2019-02-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0002_breed_date_added'),
        ('breed_group', '0003_breedgroup_breeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedgroup',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breed.Breed'),
        ),
    ]
