# Generated by Django 2.1.7 on 2019-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('admin_users', models.IntegerField()),
                ('read_only_users', models.IntegerField()),
                ('number_of_animals', models.IntegerField()),
                ('multi_breed', models.BooleanField()),
                ('support', models.BooleanField()),
                ('support_cost_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_price_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
