# Generated by Django 2.1.9 on 2019-06-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('service', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=500)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('service_name', models.CharField(max_length=50)),
                ('admin_users', models.IntegerField()),
                ('read_only_users', models.IntegerField()),
                ('number_of_animals', models.IntegerField()),
                ('multi_breed', models.BooleanField()),
                ('support', models.BooleanField()),
                ('support_cost_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_price_per_year', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_description', models.TextField()),
                ('service_id', models.CharField(blank=True, max_length=100)),
                ('monthly_id', models.CharField(blank=True, max_length=100)),
                ('yearly_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
