# Generated by Django 2.1.7 on 2019-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
