# Generated by Django 2.1.7 on 2019-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0002_service_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='total_price_per_year',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
