# Generated by Django 2.1.7 on 2019-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0003_auto_20190510_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
