# Generated by Django 2.1.10 on 2019-07-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_lines.Service'),
        ),
    ]
