# Generated by Django 2.2.11 on 2020-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
