# Generated by Django 2.1.7 on 2019-05-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0004_service_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordering']},
        ),
    ]
