# Generated by Django 2.1.10 on 2019-07-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud_lines', '0004_auto_20190721_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeTierQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_state', models.CharField(choices=[('waiting', 'Waiting'), ('building', 'Building'), ('complete', 'Complete')], default='waiting', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
