# Generated by Django 2.2.11 on 2020-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0005_auto_20200907_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
