# Generated by Django 2.1.10 on 2019-07-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190721_1838'),
        ('cloud_lines', '0005_largetierqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='largetierqueue',
            name='AttachedService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lattached_service', to='account.AttachedService'),
        ),
        migrations.AddField(
            model_name='largetierqueue',
            name='user_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to='account.UserDetail'),
        ),
    ]
