# Generated by Django 2.2.11 on 2020-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0006_bolton'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolton',
            name='visible_to_public',
            field=models.BooleanField(default=True),
        ),
    ]
