# Generated by Django 2.1.7 on 2019-05-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0006_auto_20190510_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordering']},
        ),
    ]
