# Generated by Django 2.1.10 on 2019-07-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0006_auto_20190729_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='largetierqueue',
            old_name='AttachedService',
            new_name='attached_service',
        ),
    ]
