# Generated by Django 2.1.10 on 2019-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0007_auto_20190729_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='largetierqueue',
            name='build_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='largetierqueue',
            name='subdomain',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
