# Generated by Django 2.1.7 on 2019-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0007_auto_20190510_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
