# Generated by Django 2.2.24 on 2021-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0007_bolton_visible_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolton',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
