# Generated by Django 2.1.10 on 2019-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0008_auto_20190801_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largetierqueue',
            name='build_status',
            field=models.TextField(blank=True),
        ),
    ]
