# Generated by Django 2.1.10 on 2019-08-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0009_auto_20190802_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='largetierqueue',
            name='percentage_complete',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='largetierqueue',
            name='build_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
