# Generated by Django 2.1.7 on 2019-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0010_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sub_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
