# Generated by Django 2.1.10 on 2019-09-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0011_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['date']},
        ),
    ]
