# Generated by Django 2.1.10 on 2019-09-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0012_auto_20190908_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
