# Generated by Django 2.1.10 on 2019-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0014_auto_20190909_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='body',
            field=models.TextField(default='<ul><li>/li></ul>'),
        ),
    ]
