# Generated by Django 2.1.10 on 2019-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0015_auto_20190909_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='body',
            field=models.TextField(default='Features\n                                        <br>\n                                            <ul>\n                                                <li>/li>\n                                            </ul>\n                                        Bug Fixes\n                                            <ul>\n                                                <li>/li>\n                                            </ul>'),
        ),
    ]
