# Generated by Django 2.1.10 on 2019-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0016_auto_20190909_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='body',
            field=models.TextField(default='<strong>Features</strong>\n    <br>\n        <ul class="list-icons">\n            <li><i class="fa fa-check text-info"></i> </li>\n        </ul>\n<strong>Bug Fixes</strong>\n        <ul class="list-icons">\n            <li><i class="fa fa-check text-info"></i> </li>\n        </ul>'),
        ),
    ]
