# Generated by Django 2.2.5 on 2019-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0017_auto_20190909_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='monthly_test_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_test_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='yearly_test_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
