# Generated by Django 2.2.5 on 2019-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0018_auto_20190928_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contrib_users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
