# Generated by Django 2.2.4 on 2019-12-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_lines', '0021_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='body',
        ),
        migrations.AddField(
            model_name='gallery',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
