# Generated by Django 2.2.24 on 2021-06-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedigree', '0007_pedigree_sale_or_hire'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedigree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_notification', to='pedigree.Pedigree')),
            ],
        ),
    ]
