# Generated by Django 2.2.24 on 2021-06-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0007_pedigree_sale_or_hire'),
        ('account', '0006_attachedservice_boltons'),
        ('boltons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthnotification',
            name='pedigree',
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='comments',
            field=models.TextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='deceased_females',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='deceased_males',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnfather', to='pedigree.Pedigree'),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='living_females',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='living_males',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnmother', to='pedigree.Pedigree'),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='service_method',
            field=models.CharField(choices=[('natural_service', 'Natual Service'), ('embryo_implant', 'Embryo Implant'), ('ai', 'Artificial Insemination')], default='unknown', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
