# Generated by Django 2.2.24 on 2021-09-27 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0008_breeder_user'),
        ('boltons', '0002_auto_20210624_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeder.Breeder', verbose_name='Breeder'),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
