# Generated by Django 2.2.24 on 2021-10-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boltons', '0003_auto_20210927_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthnotification',
            name='breeder',
        ),
        migrations.RemoveField(
            model_name='birthnotification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='birthnotification',
            name='dob',
        ),
    ]
