# Generated by Django 2.2.24 on 2021-10-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_attachedservice_boltons'),
        ('boltons', '0005_auto_20211012_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='attached_bolton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedBolton', verbose_name='Attached Bolton'),
        ),
    ]
