# Generated by Django 2.2.24 on 2022-04-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boltons', '0006_birthnotification_attached_bolton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthNotification',
        ),
    ]
