# Generated by Django 2.1.7 on 2019-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('medium', 'Medium'), ('low', 'Low'), ('high', 'High')], default=None, max_length=10)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
