# Generated by Django 2.1.7 on 2019-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20190417_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting_on_customer', 'Waiting on customer'), ('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default=None, max_length=10),
        ),
    ]
