# Generated by Django 2.1.7 on 2019-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20190417_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting_on_customer', 'Waiting on customer'), ('closed', 'Closed'), ('open', 'Open')], default='open', max_length=100),
        ),
    ]
