# Generated by Django 2.1.7 on 2019-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20190420_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('waiting_on_customer', 'Waiting on customer')], default='open', max_length=100),
        ),
    ]
