# Generated by Django 2.2 on 2019-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20190503_1304'),
        ('support', '0008_auto_20190424_1801'),
    ]

    operations = [
    ]
