# Generated by Django 2.1.7 on 2019-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20190426_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_on_customer', 'Waiting on customer'), ('closed', 'Closed')], default='open', max_length=100),
        ),
    ]
