# Generated by Django 2.2 on 2019-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_auto_20190503_1305'),
        ('support', '0013_auto_20190426_1524'),
    ]

    operations = [
    ]
