# Generated by Django 2.2.4 on 2019-12-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191209_0855'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanKinshipLastRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService', verbose_name='Account')),
            ],
        ),
    ]
