# Generated by Django 2.2.11 on 2021-04-20 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_attachedservice_boltons'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilastrun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.AttachedService', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='meankinshiplastrun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.AttachedService', verbose_name='Account'),
        ),
        migrations.CreateModel(
            name='StudAdvisorQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AttachedService', verbose_name='Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
