# Generated by Django 2.2.11 on 2021-04-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20210420_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='studadvisorqueue',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
