# Generated by Django 2.2.11 on 2021-04-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0007_pedigree_sale_or_hire'),
        ('metrics', '0003_studadvisorqueue_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studadvisorqueue',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedigree.Pedigree', verbose_name='Mother'),
        ),
    ]
