# Generated by Django 2.2.11 on 2021-04-23 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_studadvisorqueue_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='studadvisorqueue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
