# Generated by Django 2.2.11 on 2021-04-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_studadvisorqueue_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studadvisorqueue',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
