# Generated by Django 2.2.11 on 2021-05-01 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedigree', '0007_pedigree_sale_or_hire'),
        ('account', '0006_attachedservice_boltons'),
        ('metrics', '0006_studadvisorqueue_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='KinshipQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=250)),
                ('email_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AttachedService', verbose_name='Account')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kfatherq', to='pedigree.Pedigree', verbose_name='Father')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kmotherq', to='pedigree.Pedigree', verbose_name='Mother')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
