# Generated by Django 2.2.11 on 2021-06-09 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_attachedservice_boltons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0008_kinshipqueue_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataValidatorQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AttachedService', verbose_name='Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
