# Generated by Django 2.2.24 on 2022-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_studadvisorqueue_mk_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='studadvisorqueue',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studadvisorqueue',
            name='failed_message',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
