# Generated by Django 2.2.24 on 2022-03-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0012_auto_20220227_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinshipqueue',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
