# Generated by Django 2.2.27 on 2022-11-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_attachedservice_pedigree_charging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='bn_child_cost_id',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='bn_cost_id',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='bn_stripe_product_id',
        ),
    ]
