# Generated by Django 2.2.27 on 2022-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20221111_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='bn_child_cost_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='bn_cost_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='bn_stripe_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='charging',
            field=models.BooleanField(default=False),
        ),
    ]
