# Generated by Django 2.2.27 on 2022-11-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20221112_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeaccount',
            old_name='charging',
            new_name='bn_charging',
        ),
    ]
