# Generated by Django 2.2.24 on 2021-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportqueue',
            name='file_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
