# Generated by Django 2.2.24 on 2021-10-27 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportqueue_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportqueue',
            name='from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportqueue',
            name='to_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
