# Generated by Django 2.2.24 on 2021-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20211027_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportqueue',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportqueue',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
