# Generated by Django 4.2.2 on 2024-05-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportqueue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportqueue',
            name='report_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
