# Generated by Django 2.2.11 on 2020-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Must be unique', max_length=100, unique=True, verbose_name='registration number'),
        ),
    ]
