# Generated by Django 2.1.5 on 2019-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedigreeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_mode', models.CharField(choices=[('hierarchy', 'Hierarchy'), ('groups', 'Groups')], default=None, max_length=10, null=True)),
            ],
        ),
    ]
