# Generated by Django 2.1.7 on 2019-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_pedigreesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
