# Generated by Django 2.1.10 on 2019-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_pedigree_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigreeattributes',
            name='eggs_per_week',
        ),
        migrations.RemoveField(
            model_name='pedigreeattributes',
            name='prize_winning',
        ),
        migrations.AddField(
            model_name='pedigreeattributes',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
    ]
