# Generated by Django 2.2.11 on 2020-06-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_auto_20200527_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedigree',
            options={'ordering': ['-date_added']},
        ),
    ]
