# Generated by Django 2.2.11 on 2020-07-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0003_auto_20200611_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedigree',
            options={'ordering': ['-reg_no']},
        ),
    ]
