# Generated by Django 2.1.7 on 2019-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0004_sitedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='install_available',
            field=models.BooleanField(default=True),
        ),
    ]
