# Generated by Django 2.1.10 on 2019-07-26 20:24

from django.db import migrations, models
import django.db.models.deletion
import pedigree.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190721_1838'),
        ('pedigree', '0004_pedigree_tag_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedigree',
            options={'get_latest_by': 'order_date'},
        ),
        migrations.AddField(
            model_name='pedigreeimage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='breed_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='breed group name'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='breeder.Breeder', verbose_name='current owner'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True, verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='pedigree.Pedigree', verbose_name='father'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='pedigree.Pedigree', verbose_name='mother'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='registration number'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='tag_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tag number'),
        ),
        migrations.AlterField(
            model_name='pedigreeimage',
            name='image',
            field=models.ImageField(upload_to=pedigree.models.user_directory_path),
        ),
    ]
