# Generated by Django 2.1.10 on 2019-07-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0005_auto_20190726_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='breed.Breed', verbose_name='breed'),
        ),
    ]
