# Generated by Django 2.1.7 on 2019-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0006_delete_sitedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreesetting',
            name='breed_mode',
            field=models.CharField(choices=[('mammal', 'Mammal'), ('poultry', 'Poultry')], default=None, max_length=10, null=True),
        ),
    ]
