# Generated by Django 2.2.11 on 2021-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0006_auto_20210330_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='sale_or_hire',
            field=models.BooleanField(default=False, help_text='Is the pedigree for sale/hire, or not?', verbose_name='For Sale/Hire'),
        ),
    ]
