# Generated by Django 2.2.24 on 2021-07-16 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0007_pedigree_sale_or_hire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigree',
            name='born_as',
        ),
        migrations.AddField(
            model_name='pedigree',
            name='litter_size',
            field=models.IntegerField(default=1, help_text='Accepted range: 1-50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Litter Size'),
        ),
    ]
