# Generated by Django 2.1.10 on 2019-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0007_auto_20190727_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('castrated', 'Castrated')], default='female', help_text='Accepted formats: male, female, castrated', max_length=10, null=True),
        ),
    ]
