# Generated by Django 2.1.7 on 2019-03-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0007_auto_20190330_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedigreeSetting',
        ),
    ]
