# Generated by Django 2.2.24 on 2021-07-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0008_pedigree_litter_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigree',
            name='born_as',
        ),
    ]
