# Generated by Django 2.1.7 on 2019-03-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0008_delete_pedigreesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='breed_group',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
