# Generated by Django 2.1.10 on 2019-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0008_auto_20190729_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Must be unique', max_length=100, unique=True, verbose_name='registration number'),
        ),
    ]
