# Generated by Django 2.1.7 on 2019-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0009_pedigree_breed_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='breed_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
