# Generated by Django 2.1.10 on 2019-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0009_auto_20190801_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='parent_father_notes',
            field=models.CharField(blank=True, help_text='Max 500 characters', max_length=500, verbose_name='Father Notes'),
        ),
        migrations.AddField(
            model_name='pedigree',
            name='parent_mother_notes',
            field=models.CharField(blank=True, help_text='Max 500 characters', max_length=500, verbose_name='Mother Notes'),
        ),
    ]
