# Generated by Django 2.1.10 on 2019-08-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0010_auto_20190828_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigree',
            name='note',
        ),
    ]
