# Generated by Django 2.1.7 on 2019-04-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0010_auto_20190405_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='parent_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='pedigree.Pedigree'),
        ),
    ]
