# Generated by Django 2.2.27 on 2022-11-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0010_pedigree_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='stripe_payment_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
