# Generated by Django 2.1.7 on 2019-04-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0011_auto_20190407_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeder.Breeder'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='breeder.Breeder'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='pedigree.Pedigree'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='pedigree.Pedigree'),
        ),
        migrations.AlterField(
            model_name='pedigreeimage',
            name='reg_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='pedigree.Pedigree'),
        ),
    ]
