# Generated by Django 2.1.10 on 2019-08-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0011_remove_pedigree_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='parent_father_notes',
            field=models.CharField(blank=True, help_text='Max 500 characters', max_length=500, null=True, verbose_name='Father Notes'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent_mother_notes',
            field=models.CharField(blank=True, help_text='Max 500 characters', max_length=500, null=True, verbose_name='Mother Notes'),
        ),
    ]
