# Generated by Django 2.2.5 on 2019-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0012_auto_20190829_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='status',
            field=models.CharField(choices=[('dead', 'Dead'), ('alive', 'Alive'), ('unknown', 'Unknown')], default='alive', help_text='Accepted formats: dead, alive, unknown', max_length=10, null=True),
        ),
    ]
