# Generated by Django 2.2.5 on 2019-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0013_pedigree_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='status',
            field=models.CharField(choices=[('dead', 'Dead'), ('alive', 'Alive'), ('unknown', 'Unknown')], default='unknown', help_text='Accepted formats: dead, alive, unknown', max_length=10, null=True),
        ),
    ]
