# Generated by Django 2.2.5 on 2019-10-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0014_auto_20190923_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='breed_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Breed group name'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='breeder',
            field=models.ForeignKey(blank=True, help_text='Often the same as Current Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeder.Breeder', verbose_name='Breeder'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='description',
            field=models.TextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attribute', serialize=False, to='pedigree.Pedigree', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='pedigreeimage',
            name='reg_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='pedigree.Pedigree', verbose_name='Image'),
        ),
    ]
