# Generated by Django 2.2.5 on 2019-10-16 21:01

from django.db import migrations, models
import pedigree.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0015_auto_20191016_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeimage',
            name='image',
            field=models.ImageField(upload_to=pedigree.models.user_directory_path, verbose_name='Image'),
        ),
    ]
