# Generated by Django 2.2.5 on 2019-10-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0016_auto_20191016_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService', verbose_name='Account'),
        ),
    ]
