# Generated by Django 2.2.5 on 2019-10-16 21:12

from django.db import migrations, models
import django.db.models.deletion
import pedigree.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0017_auto_20191016_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='breed.Breed'),
        ),
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attribute', serialize=False, to='pedigree.Pedigree'),
        ),
        migrations.AlterField(
            model_name='pedigreeimage',
            name='image',
            field=models.ImageField(upload_to=pedigree.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='pedigreeimage',
            name='reg_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='pedigree.Pedigree'),
        ),
    ]
