# Generated by Django 2.2.5 on 2019-10-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0018_auto_20191016_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
