# Generated by Django 2.2.5 on 2019-10-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0019_pedigree_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigree',
            name='approved',
        ),
    ]
