# Generated by Django 2.2.5 on 2019-10-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0020_remove_pedigree_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='state',
            field=models.CharField(choices=[('edited', 'Edited'), ('unapproved', 'Unapproved'), ('approved', 'Approved')], default='approved', max_length=10, null=True),
        ),
    ]
