# Generated by Django 2.2.5 on 2019-10-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0005_auto_20190811_2028'),
        ('pedigree', '0021_pedigree_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='breed.Breed'),
        ),
        migrations.AddField(
            model_name='pedigree',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PedigreeAttributes',
        ),
    ]
