# Generated by Django 2.2.5 on 2019-11-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0022_auto_20191022_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigreeimage',
            name='state',
            field=models.CharField(choices=[('edited', 'Edited'), ('unapproved', 'Unapproved'), ('approved', 'Approved')], default='approved', max_length=10, null=True),
        ),
    ]
