# Generated by Django 2.2.4 on 2019-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0023_pedigreeimage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='coi',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
