# Generated by Django 2.2.4 on 2019-12-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0024_pedigree_coi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='coi',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5),
        ),
    ]
