# Generated by Django 2.2.4 on 2019-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0025_auto_20191203_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='mean_kinship',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='coi',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5),
        ),
    ]
