# Generated by Django 2.2.4 on 2019-12-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0027_auto_20191209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='breed.Breed'),
        ),
    ]
