# Generated by Django 2.2.4 on 2019-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0028_auto_20191209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Must be unique', max_length=100, verbose_name='registration number'),
        ),
    ]
