# Generated by Django 2.2.11 on 2020-04-16 14:09

from django.db import migrations, models
import django.db.models.deletion
import impex.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ImageField(upload_to=impex.models.user_directory_path)),
                ('file_type', models.CharField(choices=[('.csv', '.csv')], default=None, max_length=5, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
            ],
        ),
    ]
