# Generated by Django 2.2.24 on 2021-07-02 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseupload',
            name='database',
        ),
        migrations.RemoveField(
            model_name='databaseupload',
            name='file_type',
        ),
        migrations.AddField(
            model_name='databaseupload',
            name='created_objects',
            field=models.TextField(default={'created_objects': []}),
        ),
        migrations.AddField(
            model_name='databaseupload',
            name='errors',
            field=models.TextField(default={'invalid': [], 'missing': []}),
        ),
        migrations.AddField(
            model_name='databaseupload',
            name='existing',
            field=models.TextField(default={'existing': []}),
        ),
        migrations.AddField(
            model_name='databaseupload',
            name='header',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databaseupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='databaseupload',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.AttachedService'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_slice', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('.csv', '.csv')], default='.csv', max_length=5, null=True)),
                ('used', models.BooleanField(default=False)),
                ('database_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_slice', to='impex.DatabaseUpload')),
            ],
        ),
    ]
