# Generated by Django 2.2.24 on 2021-07-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0002_auto_20210702_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseupload',
            name='created_objects',
        ),
        migrations.RemoveField(
            model_name='databaseupload',
            name='existing',
        ),
    ]
