# Generated by Django 2.2.24 on 2021-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0003_auto_20210705_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseupload',
            name='total_lines',
            field=models.IntegerField(null=True),
        ),
    ]
