# Generated by Django 2.2.24 on 2021-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0005_exportqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportqueue',
            name='download_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
