# Generated by Django 2.2.24 on 2021-08-29 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0006_exportqueue_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportqueue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
