# Generated by Django 2.2.24 on 2021-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0007_exportqueue_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportqueue',
            name='status',
        ),
        migrations.AddField(
            model_name='exportqueue',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
