# Generated by Django 2.2.27 on 2022-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0020_bnsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnsettings',
            name='bn_child_cost_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bnsettings',
            name='bn_cost_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bnsettings',
            name='bn_stripe_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
