# Generated by Django 2.2.27 on 2022-11-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0021_auto_20221111_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BnSettings',
        ),
    ]
