# Generated by Django 2.2.24 on 2022-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthnotification',
            name='service_method',
            field=models.CharField(choices=[('natural_service', 'Natual Service'), ('embryo_implant', 'Embryo Implant'), ('ai', 'Artificial Insemination')], default='unknown', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
