# Generated by Django 2.2.24 on 2022-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0003_auto_20220416_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnchild',
            name='status',
            field=models.CharField(choices=[('deceased', 'Deceased'), ('alive', 'Alive')], default='unknown', help_text='Accepted formats: dead, alive, unknown', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
