# Generated by Django 2.2.24 on 2022-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0004_auto_20220416_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnchild',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='bnchild',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bnchild',
            name='tag_no',
            field=models.CharField(blank=True, help_text='Must be unique', max_length=100, verbose_name='Tag Number'),
        ),
    ]
