# Generated by Django 2.2.24 on 2022-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0005_auto_20220421_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
