# Generated by Django 2.2.27 on 2022-08-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0009_auto_20210718_1500'),
        ('birth_notifications', '0009_bnstripeaccount_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnchild',
            name='comments',
            field=models.TextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='bnchild',
            name='pedigree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_ped', to='pedigree.Pedigree'),
        ),
    ]
