# Generated by Django 2.2.27 on 2022-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0011_auto_20220823_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
