# Generated by Django 2.2.27 on 2022-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0012_birthnotification_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='stripe_payment_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='birthnotification',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth(s)'),
        ),
    ]
