# Generated by Django 2.2.27 on 2022-09-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0014_birthnotification_stripe_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnchild',
            name='for_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
