# Generated by Django 2.2.27 on 2022-10-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0016_auto_20221004_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BnStripeAccount',
        ),
    ]
