# Generated by Django 2.2.27 on 2022-10-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_notifications', '0017_delete_bnstripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
