# Generated by Django 2.2.27 on 2022-11-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0008_breeder_user'),
        ('birth_notifications', '0019_remove_birthnotification_stripe_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeder.Breeder', verbose_name='Breeder'),
        ),
    ]
