# Generated by Django 2.2.9 on 2020-04-15 07:39

import breed.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=breed.models.user_directory_path)),
                ('breed_description', models.TextField(blank=True, max_length=2000)),
                ('custom_fields', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('mk_threshold', models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='This value dictates how potential males are selected when comparedwith females. The MK value of the selected female, plus or minus this figure, determines the acceptable range of MK values in the male population, for a breeding match.', max_digits=6, null=True, verbose_name='Mean Kinship threshold')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService')),
            ],
        ),
    ]
