# Generated by Django 2.2.24 on 2021-08-17 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='breed_admins',
            field=models.ManyToManyField(blank=True, related_name='breed_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
