# Generated by Django 2.1.10 on 2019-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
