# Generated by Django 2.1.10 on 2019-07-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0002_auto_20190706_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='description',
            new_name='breed_description',
        ),
    ]
