# Generated by Django 2.1.7 on 2019-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0002_breed_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
