# Generated by Django 2.1.10 on 2019-07-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0003_auto_20190706_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='custom_fields',
            field=models.TextField(blank=True),
        ),
    ]
