# Generated by Django 2.1.7 on 2019-04-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0003_breed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
