# Generated by Django 2.1.10 on 2019-08-11 20:28

import breed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0004_breed_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, upload_to=breed.models.user_directory_path),
        ),
    ]
