# Generated by Django 2.2.4 on 2019-12-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0005_auto_20190811_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='mk_a',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Mean Kinship Group A'),
        ),
        migrations.AddField(
            model_name='breed',
            name='mk_b',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Mean Kinship Group B'),
        ),
        migrations.AddField(
            model_name='breed',
            name='mk_c',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Mean Kinship Group C'),
        ),
    ]
