# Generated by Django 2.2.4 on 2019-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0006_auto_20191209_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='mk_b',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5, verbose_name='Mean Kinship Group B'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mk_c',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=5, verbose_name='Mean Kinship Group C'),
        ),
    ]
