# Generated by Django 2.2.4 on 2019-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0007_auto_20191209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='mk_a',
            field=models.FloatField(default=0.0, verbose_name='Mean Kinship Group A'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mk_b',
            field=models.FloatField(default=0.01, verbose_name='Mean Kinship Group B'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mk_c',
            field=models.FloatField(default=0.02, verbose_name='Mean Kinship Group C'),
        ),
    ]
