# Generated by Django 2.2.4 on 2019-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0010_auto_20191209_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='mk_d',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=6, verbose_name='Mean Kinship Group D'),
        ),
    ]
