# Generated by Django 2.2.4 on 2019-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0011_breed_mk_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='mk_a',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Mean Kinship Group A'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mk_b',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Mean Kinship Group B'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mk_c',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Mean Kinship Group C'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mk_d',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Mean Kinship Group D'),
        ),
    ]
