# Generated by Django 2.2.9 on 2020-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0014_auto_20191217_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='mk_a',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='mk_b',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='mk_c',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='mk_d',
        ),
        migrations.AddField(
            model_name='breed',
            name='mk_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Mean Kinship threshold'),
        ),
    ]
