# Generated by Django 2.2.9 on 2020-03-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0015_auto_20200303_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='mk_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='This value dictates how potential males are selected when comparedwith females. The MK value of the selected female, plus or minus this figure, determines the acceptable range of MK values in the male population, for a breeding match.', max_digits=6, null=True, verbose_name='Mean Kinship threshold'),
        ),
    ]
