# Generated by Django 2.2.5 on 2019-10-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
