# Generated by Django 2.2.5 on 2019-10-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_attachedservice_domain'),
        ('approvals', '0002_approval_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AttachedService', verbose_name='account'),
        ),
    ]
