# Generated by Django 2.2.5 on 2019-10-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approval_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
