# Generated by Django 2.2.5 on 2019-10-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0004_auto_20190728_2030'),
        ('breed_group', '0001_initial'),
        ('approvals', '0004_approval_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='breed_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breed_group.BreedGroup', verbose_name='breed_group'),
        ),
        migrations.AddField(
            model_name='approval',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeder.Breeder', verbose_name='breeder'),
        ),
    ]
