# Generated by Django 2.2.5 on 2019-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_auto_20191021_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
