# Generated by Django 2.2.5 on 2019-10-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_auto_20191021_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
