# Generated by Django 2.2.5 on 2019-10-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_auto_20191022_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
