# Generated by Django 2.2.5 on 2019-10-24 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_approval_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
