# Generated by Django 2.2.5 on 2019-10-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0012_remove_approval_breeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='type',
            field=models.CharField(choices=[('edit', 'edit'), ('new', 'New')], default='new', max_length=10, null=True),
        ),
    ]
