# Generated by Django 2.2.5 on 2019-10-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0013_approval_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approved',
        ),
    ]
